export const videos = [
  {
    id: '1',
    title: 'What Happens If You Fall Into a Black Hole?',
    thumbnail: 'https://images.pexels.com/photos/2150/sky-space-dark-galaxy.jpg?auto=compress&cs=tinysrgb&w=800',
    duration: '10:47',
    views: '2.4M',
    uploadDate: '2 days ago',
    category: 'Space',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '2',
    title: 'The Dark Truth Behind Ancient Civilizations',
    thumbnail: 'https://images.pexels.com/photos/3199516/pexels-photo-3199516.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '8:21',
    views: '1.8M',
    uploadDate: '5 days ago',
    category: 'History',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '3',
    title: "Why We Haven't Found Aliens Yet? The Fermi Paradox",
    thumbnail: 'https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '12:33',
    views: '3.1M',
    uploadDate: '1 week ago',
    category: 'Mysteries',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '4',
    title: 'The Ice Age Was More Terrifying Than You Think',
    thumbnail: 'https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '9:16',
    views: '987K',
    uploadDate: '2 weeks ago',
    category: 'Science',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '5',
    title: 'How Your Brain Creates False Memories',
    thumbnail: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '11:02',
    views: '1.5M',
    uploadDate: '3 weeks ago',
    category: 'Psychology',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '6',
    title: 'The Ocean Floor Hides Civilizations Older Than Egypt',
    thumbnail: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '13:45',
    views: '2.2M',
    uploadDate: '1 month ago',
    category: 'Mysteries',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '7',
    title: 'Quantum Physics Proves Reality is an Illusion',
    thumbnail: 'https://images.pexels.com/photos/956999/milky-way-starry-sky-night-sky-star-956999.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '15:18',
    views: '4.7M',
    uploadDate: '1 month ago',
    category: 'Science',
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: '8',
    title: 'AI Will Be Smarter Than All Humans Combined By 2030',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '14:22',
    views: '3.9M',
    uploadDate: '6 weeks ago',
    category: 'Technology',
    youtubeId: 'dQw4w9WgXcQ',
  },
];

export const articles = [
  {
    id: '1',
    title: 'The Most Mysterious Planets in the Universe You Never Heard Of',
    excerpt: 'Beyond our solar system lie worlds so strange they defy every law of physics we thought we understood. From planets raining iron to ones made entirely of diamond.',
    thumbnail: 'https://images.pexels.com/photos/41162/moon-landing-apollo-11-nasa-buzz-aldrin-41162.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Space',
    readTime: '5 min read',
    date: 'Dec 28, 2024',
    slug: 'mysterious-planets-universe',
  },
  {
    id: '2',
    title: 'Why Humans Believe in Things Without Proof: The Psychology of Faith',
    excerpt: 'Deep within the human mind lies a paradox — we are the most rational species on Earth, yet we believe in things that cannot be proven. Science finally has an answer.',
    thumbnail: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Psychology',
    readTime: '6 min read',
    date: 'Dec 25, 2024',
    slug: 'psychology-of-belief',
  },
  {
    id: '3',
    title: 'The Lost Continent That Existed Before Written History',
    excerpt: "Beneath the Indian Ocean lies the remnants of a landmass that sank 84 million years ago. But traces of its existence keep resurfacing — and they're changing everything.",
    thumbnail: 'https://images.pexels.com/photos/3199516/pexels-photo-3199516.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'History',
    readTime: '8 min read',
    date: 'Dec 22, 2024',
    slug: 'lost-continent-before-history',
  },
  {
    id: '4',
    title: 'Nature\'s Most Impossible Engineering: How Trees Actually Work',
    excerpt: 'A 100-meter-tall tree moves water from roots to leaves against gravity without a pump. The mechanism behind this defies simple explanation — and it took centuries to discover.',
    thumbnail: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Nature',
    readTime: '7 min read',
    date: 'Dec 18, 2024',
    slug: 'how-trees-work',
  },
  {
    id: '5',
    title: 'The Technology That Will Make Human Aging Optional',
    excerpt: 'Senolytic therapies, gene editing, and cellular reprogramming are no longer science fiction. The first person to live to 1000 may already be alive today.',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Technology',
    readTime: '9 min read',
    date: 'Dec 14, 2024',
    slug: 'technology-reverse-aging',
  },
  {
    id: '6',
    title: "The Voynich Manuscript: A 600-Year-Old Book Nobody Can Read",
    excerpt: "For over six centuries, this illustrated medieval manuscript has defied every attempt at deciphering. It contains a language that doesn't exist — or does it?",
    thumbnail: 'https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Mysteries',
    readTime: '6 min read',
    date: 'Dec 10, 2024',
    slug: 'voynich-manuscript',
  },
];

export const categories = [
  { name: 'Science', icon: 'Atom', count: 47, color: '#00D9FF', gradient: 'from-cyan-500/20 to-blue-500/10' },
  { name: 'Space', icon: 'Orbit', count: 38, color: '#8B5CF6', gradient: 'from-violet-500/20 to-purple-500/10' },
  { name: 'History', icon: 'Landmark', count: 29, color: '#F59E0B', gradient: 'from-amber-500/20 to-orange-500/10' },
  { name: 'Psychology', icon: 'Brain', count: 33, color: '#EC4899', gradient: 'from-pink-500/20 to-rose-500/10' },
  { name: 'Mysteries', icon: 'Eye', count: 42, color: '#10B981', gradient: 'from-emerald-500/20 to-teal-500/10' },
  { name: 'Technology', icon: 'Cpu', count: 25, color: '#3B82F6', gradient: 'from-blue-500/20 to-indigo-500/10' },
  { name: 'Nature', icon: 'Leaf', count: 18, color: '#22C55E', gradient: 'from-green-500/20 to-emerald-500/10' },
];

export const series = [
  {
    id: '1',
    title: 'Space Mysteries',
    description: 'The universe\'s darkest and most fascinating secrets, from black holes to dark matter.',
    thumbnail: 'https://images.pexels.com/photos/2150/sky-space-dark-galaxy.jpg?auto=compress&cs=tinysrgb&w=800',
    episodeCount: 12,
    category: 'Space',
  },
  {
    id: '2',
    title: 'Human Psychology',
    description: 'Exploring the deepest mechanisms of the human mind — from dreams to manipulation.',
    thumbnail: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    episodeCount: 9,
    category: 'Psychology',
  },
  {
    id: '3',
    title: 'Ancient Civilizations',
    description: 'Uncovering the truth behind ancient societies that were far more advanced than we believed.',
    thumbnail: 'https://images.pexels.com/photos/3199516/pexels-photo-3199516.jpeg?auto=compress&cs=tinysrgb&w=800',
    episodeCount: 15,
    category: 'History',
  },
  {
    id: '4',
    title: 'Impossible Places',
    description: 'Real locations on Earth so extraordinary they seem like they were pulled from another dimension.',
    thumbnail: 'https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?auto=compress&cs=tinysrgb&w=800',
    episodeCount: 8,
    category: 'Mysteries',
  },
  {
    id: '5',
    title: 'Future Technology',
    description: 'The technologies being built right now that will completely redefine what it means to be human.',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    episodeCount: 11,
    category: 'Technology',
  },
  {
    id: '6',
    title: 'Ocean Secrets',
    description: 'We know more about the surface of Mars than our own ocean floors. What are we missing?',
    thumbnail: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    episodeCount: 7,
    category: 'Nature',
  },
];

export const testimonials = [
  {
    id: '1',
    name: 'Arjun Sharma',
    handle: '@arjun_curious',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=100',
    text: 'Fact Syntax is the only channel that makes me question everything I thought I knew. Every video feels like a documentary you\'d pay to watch on Netflix.',
    stars: 5,
  },
  {
    id: '2',
    name: 'Priya Nair',
    handle: '@priya_learner',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=100',
    text: 'The production quality, the script, the facts — everything is just insane. I watched 6 videos in one sitting and still wanted more.',
    stars: 5,
  },
  {
    id: '3',
    name: 'Rahul Verma',
    handle: '@rahul_space_nerd',
    avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=100',
    text: '"Reality isn\'t real. Facts are." — this tagline is so accurate. Changed how I see the world after watching the quantum physics episode.',
    stars: 5,
  },
  {
    id: '4',
    name: 'Aisha Khan',
    handle: '@aisha_reads_everything',
    avatar: 'https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=100',
    text: 'I recommend Fact Syntax to everyone. Especially the psychology and history series — absolutely mind-blowing. Best educational content on YouTube.',
    stars: 5,
  },
  {
    id: '5',
    name: 'Dev Patel',
    handle: '@dev_tech_fan',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100',
    text: 'The way Fact Syntax explains complex science topics in a cinematic way is unmatched. Every video leaves me wanting to learn more.',
    stars: 5,
  },
  {
    id: '6',
    name: 'Sara Mehta',
    handle: '@sara_curious_mind',
    avatar: 'https://images.pexels.com/photos/1542085/pexels-photo-1542085.jpeg?auto=compress&cs=tinysrgb&w=100',
    text: 'Stumbled upon Fact Syntax at 11 PM, it\'s now 3 AM and I have no regrets. The black hole video broke my brain in the best way possible.',
    stars: 5,
  },
];

export const faqs = [
  {
    question: 'How often does Fact Syntax upload new videos?',
    answer: 'We upload 2–3 videos per week, typically on Monday, Wednesday, and Saturday. Subscribe and hit the notification bell to never miss a new upload.',
  },
  {
    question: 'What topics does Fact Syntax cover?',
    answer: 'We cover a wide range of topics including space, science, psychology, history, ancient civilizations, modern mysteries, nature, and emerging technology — always with a cinematic, documentary-style approach.',
  },
  {
    question: 'Can I suggest a topic for a video?',
    answer: 'Absolutely! We love hearing from our community. You can suggest topics through our community posts on YouTube, or reach out via the Contact page. Many of our most popular videos were inspired by viewer suggestions.',
  },
  {
    question: 'Are the facts in the videos verified and sourced?',
    answer: 'Yes. Every claim in our videos is rigorously researched and verified using peer-reviewed studies, credible scientific sources, and expert references. We take accuracy very seriously.',
  },
  {
    question: 'Does Fact Syntax have a community or Discord server?',
    answer: 'Yes! We have an active Discord community where curious minds gather to discuss facts, share ideas, and debate the universe\'s greatest mysteries. The link is in every video description.',
  },
  {
    question: 'Is the content available in other languages?',
    answer: 'Currently, our primary content is in English and Hindi. We are working on adding subtitles and dubbed versions in more languages based on viewer demand.',
  },
  {
    question: 'How can I support Fact Syntax?',
    answer: 'The best support is free — subscribe, watch, share, and comment. If you want to go further, you can join our channel membership for exclusive content, early access, and behind-the-scenes material.',
  },
];

export const timeline = [
  { year: '2020', event: 'Started the Channel', description: 'First video uploaded with zero subscribers and a dream to educate the world.', milestone: false },
  { year: '2020', event: '100 Subscribers', description: 'The first 100 people who believed in the vision before it was proven.', milestone: true },
  { year: '2021', event: '1K Subscribers', description: 'Crossed 1,000 subscribers. The community was beginning to take shape.', milestone: true },
  { year: '2021', event: 'First Viral Video', description: 'Our black hole video hit 500K views overnight and changed everything.', milestone: false },
  { year: '2022', event: '10K Subscribers', description: 'YouTube Silver Play Button unlocked. The channel was officially growing.', milestone: true },
  { year: '2022', event: 'Redesigned Format', description: 'Adopted the cinematic documentary format that defines Fact Syntax today.', milestone: false },
  { year: '2023', event: '100K Subscribers', description: 'YouTube Silver Play Button received. A milestone that proved the mission.', milestone: true },
  { year: '2024', event: '500K Subscribers', description: 'Half a million curious minds. Over 80 million total views across all videos.', milestone: true },
  { year: '2025+', event: 'Future Vision', description: 'Expanding to original documentaries, merchandise, and a global platform.', milestone: false },
];

export const stats = [
  { label: 'Subscribers', value: 500000, display: '500K+', suffix: '' },
  { label: 'Total Views', value: 80000000, display: '80M+', suffix: '' },
  { label: 'Facts Covered', value: 120, display: '120+', suffix: '' },
  { label: 'Videos', value: 87, display: '87', suffix: '' },
  { label: 'Countries Reached', value: 148, display: '148', suffix: '' },
  { label: 'Years of Curiosity', value: 4, display: '4+', suffix: '' },
];

export const projects = [
  {
    id: '1',
    title: 'The Universe Map',
    description: 'An interactive visualization of the observable universe, from quantum particles to cosmic filaments.',
    thumbnail: 'https://images.pexels.com/photos/2150/sky-space-dark-galaxy.jpg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Interactive', 'Space', 'Data Viz'],
    status: 'Live',
    url: '#',
  },
  {
    id: '2',
    title: 'Fact Database',
    description: 'A searchable database of 1000+ verified facts curated from all Fact Syntax episodes.',
    thumbnail: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Database', 'Search', 'Education'],
    status: 'Beta',
    url: '#',
  },
  {
    id: '3',
    title: 'Mind Explorer Quiz',
    description: 'Test your knowledge across science, history, space and psychology with adaptive difficulty.',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Quiz', 'Interactive', 'Learning'],
    status: 'Coming Soon',
    url: '#',
  },
  {
    id: '4',
    title: 'Timeline of Humanity',
    description: 'An immersive interactive timeline spanning from the Big Bang to the present day.',
    thumbnail: 'https://images.pexels.com/photos/3199516/pexels-photo-3199516.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['History', 'Interactive', 'Timeline'],
    status: 'In Progress',
    url: '#',
  },
];
